# https://taskfile.dev/
version: '3'
tasks:

  install:
    sources:
      - requirements.txt
    cmds:
      - python3 -m pip install --user -U -r requirements.txt

  generate:
    deps:
      - install
    sources:
      - data/*.yml
      - templates/*.html.j2
    cmds:
      - python3 generate.py
